<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">

    <title>
        Borrowing Report
    </title>

    <style>

        *{
            font-family: DejaVu Sans, sans-serif;
        }

        body{
            font-size:12px;
            color:#333;
        }

        h1,h2,h3,h4{
            margin:0;
        }

        table{
            width:100%;
            border-collapse:collapse;
        }

        th{
            background:#E31E24;
            color:white;
            padding:8px;
            border:1px solid #ddd;
            font-size:11px;
        }

        td{
            border:1px solid #ddd;
            padding:8px;
            font-size:11px;
        }

        .summary{
            margin:20px 0;
        }

        .summary td{
            width:25%;
            text-align:center;
            font-weight:bold;
        }

        .title{
            text-align:center;
            margin-bottom:20px;
        }

        .title p{
            margin:4px 0;
        }

        .footer{
            margin-top:25px;
            font-size:10px;
            color:#666;
            text-align:right;
        }

        .badge{

            display:inline-block;

            padding:4px 8px;

            border-radius:4px;

            font-size:10px;

            font-weight:bold;

        }

        .borrowed{

            background:#FEF3C7;

            color:#92400E;

        }

        .returned{

            background:#DCFCE7;

            color:#166534;

        }

        .overdue{

            background:#FEE2E2;

            color:#991B1B;

        }

    </style>

</head>

<body>

    {{-- Header --}}
    <div class="title">

        <h2>
            TELKOM INDONESIA
        </h2>

        <h1>
            Inventory Management System
        </h1>

        <p>
            Borrowing Report
        </p>

        <p>
            Generated :
            {{ now()->format('d F Y H:i') }}
        </p>

    </div>


    {{-- Summary --}}

    <table class="summary">

        <tr>

            <td>

                Total Borrowings

                <br><br>

                {{ $totalBorrowings }}

            </td>

            <td>

                Borrowed

                <br><br>

                {{ $borrowedCount }}

            </td>

            <td>

                Returned

                <br><br>

                {{ $returnedCount }}

            </td>

            <td>

                Overdue

                <br><br>

                {{ $overdueCount }}

            </td>

        </tr>

    </table>


    {{-- Table --}}

    <table>

        <thead>

            <tr>

                <th>No</th>

                <th>Code</th>

                <th>Borrower</th>

                <th>Department</th>

                <th>Items</th>

                <th>Borrow Date</th>

                <th>Return Date</th>

                <th>Status</th>

            </tr>

        </thead>

        <tbody>

        @forelse($borrowings as $index => $borrowing)

            <tr>

                <td>

                    {{ $index + 1 }}

                </td>

                <td>

                    {{ $borrowing->borrowing_code }}

                </td>

                <td>

                    {{ $borrowing->borrower_name }}

                </td>

                <td>

                    {{ $borrowing->department->name }}

                </td>

                <td>

                    @foreach($borrowing->details as $detail)

                        • {{ $detail->product->name }}

                        ({{ $detail->quantity }})

                        <br>

                    @endforeach

                </td>

                <td>

                    {{ $borrowing->borrow_date->format('d M Y') }}

                </td>

                <td>

                    {{ $borrowing->return_date->format('d M Y') }}

                </td>

                <td>

                    {{ $borrowing->status }}

                </td>

            </tr>

        @empty

            <tr>

                <td colspan="8" style="text-align:center">

                    No borrowing data found.

                </td>

            </tr>

        @endforelse

        </tbody>

    </table>

    <div class="footer">

        Generated by Inventory Management System

        <br>

        {{ auth()->user()->name }}

    </div>

</body>

</html>